name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info? (github username, email, etc.)
      placeholder: ex. pitzzahh
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 0.0.6.0
        - 0.0.7.0
        - 0.0.8.0
        - 0.0.9.0 (Latest)
    validations:
      required: true
  - type: dropdown
    id: problems
    attributes:
      label: What common problems did you encounter?
      multiple: true
      options:
        - Resolving URL
        - Selecting Video Quality
        - Selecting Audio Quality
        - Selecting audio only
        - Downloading
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, paste any relevant error output here.
      render: Text
